### ISSUE TITLE
Null reference issue

### ISSUE THREAD

**Issue by Jogai** [andrewlock/dotnet-config2json#4]
At first I got a helpful message about unity, but when I stripped unity out of my config I was left with a generic exception so then I stripped all sections except the microsfoft ones but still got a generic exception. 

It works if I strip it down to connectionstring and appsettings. Is that expected?

```
$ dotnet config2json Web.config
Checking 'Web.config'...
Path 'Web.config' is a file
Migrating Web.config...
None of the parsers could parse [<unity configSource="config\Unity.config" />]!
An error occurred migrating Web.config:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.AddToDictionary(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 146
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 85
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 103
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.Load() in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 85
   at Config2Json.FileMigrator.MigrateFile(String file) in C:\projects\dotnet-config2json\src\dotnet-config2json\FileMigrator.cs:line 53
Migration complete.

jogai@myPc C:\SRC\myProj\myProj.Web\myProj.Web
$ dotnet config2json Web.config
Checking 'Web.config'...
Path 'Web.config' is a file
Migrating Web.config...
An error occurred migrating Web.config:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.AddToDictionary(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 146
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 85
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 103
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.Load() in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 85
   at Config2Json.FileMigrator.MigrateFile(String file) in C:\projects\dotnet-config2json\src\dotnet-config2json\FileMigrator.cs:line 53
Migration complete.

jogai@myPc C:\SRC\myProj\myProj.Web\myProj.Web
$ dotnet config2json Web.config
Checking 'Web.config'...
Path 'Web.config' is a file
Migrating Web.config...
An error occurred migrating Web.config:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.AddToDictionary(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 146
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 85
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.KeyValueParser.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\KeyValueParser.cs:line 104
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.ParseElement(XElement element, Stack`1 context, SortedDictionary`2 results) in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 103
   at Microsoft.Extensions.Configuration.ConfigFile.ConfigFileConfigurationProvider.Load() in C:\projects\dotnet-config2json\src\dotnet-config2json\Parser\ConfigFileConfigurationProvider.cs:line 85
   at Config2Json.FileMigrator.MigrateFile(String file) in C:\projects\dotnet-config2json\src\dotnet-config2json\FileMigrator.cs:line 53
Migration complete.

**Comment by andrewlock** [comment]
That's a good question! I've only really tested it on connectionstring and appsettings as you say.  Do you have an example of a file that reproduces the issue?

**Comment by Jogai** [comment]
It was a MVC5 project with nlog & entity framework config. I think the tool would be already better if it reports that it encounters unrecognized sections and cant finish.

**Comment by andrewlock** [comment]
I agree - the key-value-parser was taken from the https://github.com/aspnet/Entropy repo, so it could need some work it seems. If you could attach an example web.config I can take a look? Cheers

**Comment by Jogai** [comment]
Here is one:
https://github.com/Jogai/BoboBrowse.Net/blob/4.0.2/src/CarDemo/CarDemo/Web.config
There are a few good warnings, but also a null reference exception

**Comment by andrewlock** [comment]
Thanks for the example @Jogai - I just fixed the issue and pushed a new version. It should be available on NuGet soon!
